// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PB/v3/pkg/models/shared"
	"net/http"
)

type Meta struct {
	Pagination *shared.Pagination `json:"pagination,omitempty"`
	TraceID    *string            `json:"traceId,omitempty"`
}

func (o *Meta) GetPagination() *shared.Pagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}

func (o *Meta) GetTraceID() *string {
	if o == nil {
		return nil
	}
	return o.TraceID
}

// CreateNewBirdResponseBody - OK
type CreateNewBirdResponseBody struct {
	Data *shared.NestedBird `json:"data,omitempty"`
	Meta *Meta              `json:"meta,omitempty"`
}

func (o *CreateNewBirdResponseBody) GetData() *shared.NestedBird {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *CreateNewBirdResponseBody) GetMeta() *Meta {
	if o == nil {
		return nil
	}
	return o.Meta
}

type CreateNewBirdResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *CreateNewBirdResponseBody
}

func (o *CreateNewBirdResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateNewBirdResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateNewBirdResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateNewBirdResponse) GetObject() *CreateNewBirdResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
