// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PB/pkg/models/shared"
	"net/http"
)

type CreateLivingThingsResponse struct {
	// OK
	ComplexObject *shared.ComplexObject
	ContentType   string
	// Internal Server Error
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}

func (o *CreateLivingThingsResponse) GetComplexObject() *shared.ComplexObject {
	if o == nil {
		return nil
	}
	return o.ComplexObject
}

func (o *CreateLivingThingsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateLivingThingsResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *CreateLivingThingsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateLivingThingsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
