// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PB/pkg/models/shared"
	"net/http"
)

type DeleteAnimalsByIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteAnimalsByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteAnimalsByIDResponse struct {
	ContentType string
	// Internal Server Error
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}

func (o *DeleteAnimalsByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAnimalsByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeleteAnimalsByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAnimalsByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
