// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PB/v2/pkg/models/shared"
	"net/http"
)

type GetAllAnimalsRequest struct {
	Age   *string `queryParam:"style=form,explode=true,name=age"`
	Color *string `queryParam:"style=form,explode=true,name=color"`
	ID    *string `queryParam:"style=form,explode=true,name=id"`
	Name  *string `queryParam:"style=form,explode=true,name=name"`
}

func (o *GetAllAnimalsRequest) GetAge() *string {
	if o == nil {
		return nil
	}
	return o.Age
}

func (o *GetAllAnimalsRequest) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *GetAllAnimalsRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GetAllAnimalsRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type GetAllAnimalsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Classes []shared.Animals
}

func (o *GetAllAnimalsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllAnimalsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllAnimalsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllAnimalsResponse) GetClasses() []shared.Animals {
	if o == nil {
		return nil
	}
	return o.Classes
}
