// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PB/pkg/models/shared"
	"net/http"
)

type GetAllBirdsResponse struct {
	// OK
	Birds       []shared.Birds
	ContentType string
	// Internal Server Error
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetAllBirdsResponse) GetBirds() []shared.Birds {
	if o == nil {
		return nil
	}
	return o.Birds
}

func (o *GetAllBirdsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllBirdsResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetAllBirdsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllBirdsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
