// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"PB/pkg/models/shared"
	"net/http"
)

type UpdateAnimalsByIDRequest struct {
	Animals *shared.Animals `request:"mediaType=application/json"`
	ID      string          `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateAnimalsByIDRequest) GetAnimals() *shared.Animals {
	if o == nil {
		return nil
	}
	return o.Animals
}

func (o *UpdateAnimalsByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateAnimalsByIDResponse struct {
	// OK
	Animals *shared.Animals
	// HTTP response content type for this operation
	ContentType string
	// Internal Server Error
	Error *shared.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateAnimalsByIDResponse) GetAnimals() *shared.Animals {
	if o == nil {
		return nil
	}
	return o.Animals
}

func (o *UpdateAnimalsByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateAnimalsByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *UpdateAnimalsByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateAnimalsByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
