// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Animals struct {
	Age   *int64  `json:"age,omitempty"`
	Color *string `json:"color,omitempty"`
	ID    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
}

func (o *Animals) GetAge() *int64 {
	if o == nil {
		return nil
	}
	return o.Age
}

func (o *Animals) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *Animals) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Animals) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
