// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Birds struct {
	CanFly   *bool   `json:"canFly,omitempty"`
	ID       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	WingSpan *int64  `json:"wingSpan,omitempty"`
}

func (o *Birds) GetCanFly() *bool {
	if o == nil {
		return nil
	}
	return o.CanFly
}

func (o *Birds) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Birds) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Birds) GetWingSpan() *int64 {
	if o == nil {
		return nil
	}
	return o.WingSpan
}
