// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Error struct {
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

func (o *Error) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *Error) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
