// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Pagination struct {
	HasMore    *bool  `json:"hasMore,omitempty"`
	PageNumber *int64 `json:"pageNumber,omitempty"`
}

func (o *Pagination) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}

func (o *Pagination) GetPageNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.PageNumber
}
