// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	Key1 *string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetKey1() *string {
	if o == nil {
		return nil
	}
	return o.Key1
}
